# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:cmod_a7-35t:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/Adder.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/CONV1D_1st_Data_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/CONV1D_1st_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/CONV1D_2nd_Data_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/CONV1D_2nd_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/CONV1D_3rd_Data_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/CONV1D_3rd_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/Comparator.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/Comparator_2_into_1.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/Compute_processor.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/Data_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/FC_1st_Data_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/FC_1st_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/FC_2nd_Data_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/FC_2nd_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/MaxPool_Data_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/Multiply.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/imports/new/UART_RX.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/imports/new/UART_RX_Flow_ctrl.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/imports/new/UART_TX.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/imports/new/UART_TX_Flow_ctrl.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/Weights_RAM.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/uCode.v}
  {C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/sources_1/new/Wrapper.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/constrs_1/imports/digilent-xdc-master/Cmod-A7-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/Final Complete NN Implementation/FYP_CNN_FPGA/FYP_CNN_FPGA.srcs/constrs_1/imports/digilent-xdc-master/Cmod-A7-Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Wrapper -part xc7a35tcpg236-1 -gated_clock_conversion auto -retiming


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Wrapper.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
