webtalk_init -webtalk_dir C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/UART_Testing/UART_Testing.sim/sim_1/synth/func/xsim/xsim.dir/UART_TB_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jan 30 10:35:39 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5fcdff85-2b86-4ca5-b7cf-b8964ee1f759" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "319ce6cab2ba44559d99534e4b1098a4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7216_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3929480768 -regid "" -xml C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/UART_Testing/UART_Testing.sim/sim_1/synth/func/xsim/xsim.dir/UART_TB_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/UART_Testing/UART_Testing.sim/sim_1/synth/func/xsim/xsim.dir/UART_TB_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Lingke/Desktop/FYP/FYP_AI_on_FPGA/UART_Testing/UART_Testing.sim/sim_1/synth/func/xsim/xsim.dir/UART_TB_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
